name: Lint with flake8

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "img/**"
  pull_request:

jobs:
  black:
    name: Lint with flake8
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: flake8 nullpom  --max-line-length=88 --statistics
